# Generated by Django 4.1.7 on 2023-03-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaitenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaiten_id', models.IntegerField(db_index=True, unique=True, verbose_name='Id кайтена')),
                ('name', models.CharField(max_length=512, verbose_name='Имя')),
                ('email', models.CharField(max_length=512, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Присутствует в kaiten')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='KaitenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaiten_id', models.IntegerField(db_index=True, unique=True, verbose_name='Id кайтена')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('created', models.DateTimeField(help_text='в kaiten', verbose_name='Время создания')),
                ('updated', models.DateTimeField(help_text='в kaiten', verbose_name='Время обновления')),
                ('moved_to_progress', models.DateTimeField(blank=True, null=True, verbose_name='Перемещена в работу')),
                ('moved_to_review', models.DateTimeField(blank=True, help_text='первый раз', null=True, verbose_name='Перемещена в ревью')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kaiten_tasks.kaitenuser', verbose_name='Пользователь kaiten')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
