# Generated by Django 4.1.7 on 2023-04-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaiten_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaitenuser',
            name='active',
            field=models.BooleanField(default=True, help_text='Присутствовал ли пользователь в выгрузке из kaiten', verbose_name='Присутствует в kaiten'),
        ),
    ]
