# Generated by Django 4.1.7 on 2023-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaiten_tasks', '0002_alter_kaitenuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaitentask',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер'),
        ),
    ]
