# Generated by Django 4.1.7 on 2023-04-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaiten_tasks', '0003_kaitentask_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaitentask',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='служебное поле', null=True, verbose_name='Последнее получение истории задачи'),
        ),
    ]
